### ISSUE TITLE
Contact page - disqus

### ISSUE THREAD

**Issue by digititus** [kelyvin/caffeine-theme#1]
Hi,
Loving the theme! Nice work.
I noticed that static pages 'About' and "Home' have disqus disabled. This is great. How do I go about disabling on 'Contact' page?  Is a custom template required? page-contact.hbs for example?
Thanks

**Comment by kelyvin** [comment]
Hi Digititus, I'm glad to hear you are enjoying the theme so far! 

To answer your question, I'm guessing you want to create a "contact" static page. If that is the case, then you are correct, it is definitely easier to create a custom template for that. 

If you envision having a lot of static pages, and you want all of them to have disqus disabled, I would even suggest creating a brand new partial and have all of your static pages inherit from that partial. I could definitely do a better job in that area, so feel free to give that shot.

**Comment by digititus** [comment]
Thanks. I created page-contact.hbs with the same content as page-about.hbs and edited accordingly. Works great!

**Comment by kelyvin** [comment]
Awesome! Glad to hear it! I will close this out then.
