### ISSUE TITLE
Author Bio and Author Page

### ISSUE THREAD

**Issue by Abhi347** [kelyvin/caffeine-theme#13]
It's a feature request, but it'd be nice to have an Author bio at the bottom of every post and a separate Author Page, just like the default theme.
Thanks :-)

**Comment by kelyvin** [comment]
That's a great idea! I was thinking about this feature and was planning on implementing it when I had guest authors on my blog, but your request will compel me to get it out sooner. 

Stay tuned!

**Comment by roccomuso** [comment]
thanks! +1

**Comment by kelyvin** [comment]
Hi @Abhi347, @roccomuso, 

Huge thanks for your patience. In my latest release, I have implemented this feature, which you can find here: https://github.com/kelyvin/caffeine-theme/releases/tag/v2.9.0.

I'm still playing around the design for the author credits that's inserted at the end of every post, but I think this is a decent first attempt at it. Please check it and out and let me know if you run into issues, have any design suggestions, or if there's anything else you'd like to see!

Thanks!
