### ISSUE TITLE
Added other languages for Prismjs

### ISSUE THREAD

**Issue by antranthien** [kelyvin/caffeine-theme#14]
Hi,

I wish to add other languages support for Prismjs (Java, C#...). How should I go about doing that? I have downloaded my desired JS & CSS at http://prismjs.com/.

Thanks.

**Comment by antranthien** [comment]
I saw there was a closed issue similar to this.

**Comment by kelyvin** [comment]
No problem, check my reply for your question here: https://github.com/kelyvin/caffeine-theme/issues/7#issuecomment-239665946
