### ISSUE TITLE
Social Links

### ISSUE THREAD

**Issue by jjwedemyer** [kelyvin/caffeine-theme#15]
Hey,
could there be a way of setting the social links in a script block like this

``` html
<script>
var xyz = 'http://facebook.com/user';
</script>
```

Another thought would be to set additional info like the title and the service in an js object

``` html
<script>
var xyz = {
   service: fb,
   link:'http://face...',
   title: '',
   fa_icon: ''
};
</script>
```

**Comment by kelyvin** [comment]
Hi @jjwedemyer, thanks for the suggestion and it was definitely I've been thinking about implementing. I will add this to the roadmap and try to get this feature out as soon as I can. Stay tuned...
