### ISSUE TITLE
Test and add AMP support for Ghost 0.10.0

### ISSUE THREAD

**Issue by andrewlock** [kelyvin/caffeine-theme#18]
It looks like AMP should work out of the box, but we need to check that everything works OK in the theme and potentially to tweak it to be more consistent with the rest of the site. 

Details here: https://dev.ghost.org/custom-amp-themes/

**Comment by kelyvin** [comment]
Thanks for putting in this request and I just saw it too! Very exciting stuff!

Unrelated to this theme, but I tried upgrading to 0.9.0 over the weekend (literally a day or two before .10.0 got released) and ran into some issues with the storage adapters and lodash. I reverted back down to 0.8.0 and plan to try debug the issues with 0.9.0 and then bump up to 0.10.0 right afterwards. If all of that goes well, I will definitely be looking into the AMP features right afterwards. 

Thanks for the heads up!

**Comment by andrewlock** [comment]
Ah that's interesting, I just tried an update to 0.9.0 myself and had no problems with it, though I'm not using a custom storage adapter... I then updated to 0.10.0 and all still looked good, AMP worked perfectly and passed validation in the browser (add #development=1 to the url and inspect the dev tools console), so hopefully won't cause too many issues 😄

**Comment by andrewlock** [comment]
Just a note that disqus also supports AMP pages too - I haven't dug into it, and the  fact you need two different hosts will be a deal breaker for a lot of people, but might be nice to add support for it:)

[Disqus for Accelerated Mobile Pages (AMP)](https://github.com/disqus/disqus-install-examples/tree/master/google-amp)

**Comment by kelyvin** [comment]
Oh shoot so many new features!  

I will look into  to this as soon as I can. The past couple of months have been crazy and a combination of studying + changing jobs + traveling + moving. Haven't even had time to blog! BUT, I am almost settled in, so I appreciate your patience!

Thanks!

**Comment by andrewlock** [comment]
Congratulations on the new job! And don't feel bad, there's no pressure... That's the beauty of open source - if I needed it, I could have done a pull-request! 😄

**Comment by kelyvin** [comment]
HI @andrewlock, 

It took almost two months, but I finally took a look at the AMP features and added better customizations to the AMP layout to better unify the Caffeine theme styling,  which you can find in the latest release here: https://github.com/kelyvin/caffeine-theme/releases/tag/v2.8.0. 

I also went through the Google console to do an audit of any broken AMP pages and saw several things that I added to the theme to hopefully prevent others from falling into the same issues (e.g. iframe sizing). 

Feel free to take a look and add whatever you think will give the template a little more flair!

Thanks!
Kelvin

**Comment by andrewlock** [comment]
Thanks, and good work! I'll take a look soon (have an equally busy time at the moment!) and will check it out:smile:
