### ISSUE TITLE
How to remove disqus?

### ISSUE THREAD

**Issue by LeoAnd95** [kelyvin/caffeine-theme#23]
Hi, I'm a Ghost newbie and I come from China.
In China, people can't use Disqus normally, so I want to remove the Disqus. However when I deleted partials/disqus-comment-count.hbs & comments.hbs. The Ghost page showed 404.
I have tried to modify the code in such .hbs, but it didn't work.
Please tell me how to work it out. Thank you!

**Comment by kelyvin** [comment]
Hi, 

You're almost there! After deleting those two partials, also open up `post.hbs` and delete line 30 that referernces the `comments.hbs` partial. 

So you would want to delete the following line: https://github.com/kelyvin/caffeine-theme/blob/810ce719e45c926b8aadd7c2b1f181cc028fb333/post.hbs#L30

That should hopefully do it. Let me know if you run into any other issues!

**Comment by LeoAnd95** [comment]
@kelyvin Hi, Thanks for your help. But it doesn't work. As shown in figure, I have deleted `comments.hbs` and `disqus-comment-count.hbs`
![](http://ww2.sinaimg.cn/mw690/ac7a896fjw1f9o2grzzdij20g402h0sy.jpg)。

---

Also, I deleted line 30 that referernces the `comments.hbs` partial.
![](http://ww3.sinaimg.cn/mw690/ac7a896fjw1f9o2gs2hm0j20hj0b0t9e.jpg)

And I have `pm2 restart Ghost`. Howerver it didn't work. Maybe some codes referencing the `comments.hbs` partial but I haven't modified it.

**Comment by LeoAnd95** [comment]
In` post.hbs` the line 30 that references the comments.hbs. 

Well, I found that in `default.hbs` the line 29 that references the `disqus-comment-count.hbs`. https://github.com/kelyvin/caffeine-theme/blob/master/default.hbs#L29.
I have deleted it and it didn't show 404 again.

**Comment by kelyvin** [comment]
Awesome! Sorry it's been a while since I touched this codebase and forgot about that one too. Glad to hear you figured it out! :)
