### ISSUE TITLE
Html <sup> are not rendered properly

### ISSUE THREAD

**Issue by EKami** [kelyvin/caffeine-theme#24]
The `<sup>` html directive used to make an exponent is weird. Here is an example of what we get with the caffeine theme below:
<img width="53" alt="exponent1" src="https://cloud.githubusercontent.com/assets/4030626/20261643/fc91e284-aa5e-11e6-897f-fb07b754f889.png">

and with the casper theme:
<img width="42" alt="exponent2" src="https://cloud.githubusercontent.com/assets/4030626/20261653/087cc4ec-aa5f-11e6-871b-71613c754276.png">

with the code: `NO<sup>1</sup>`
The one with the caffeine theme looks more like a "minus 1" instead of an exponent.

**Comment by kelyvin** [comment]
Hi @EKami, 

I have fixed this in the latest release and thanks for bringing this to my attention! You can find that here: https://github.com/kelyvin/caffeine-theme/releases/tag/v2.7.8 

Thanks!
Kelvin

**Comment by EKami** [comment]
Thanks a lot @kelyvin :)
