### ISSUE TITLE
Some texts are out of bounds

### ISSUE THREAD

**Issue by EKami** [kelyvin/caffeine-theme#26]
Hello,
Some of the texts including news and tables are sometimes out of boundaries.
Here is an example of what I get on the desktop rendering (chrome):
<img width="1159" alt="tuatini_s_blog1" src="https://cloud.githubusercontent.com/assets/4030626/21081060/e0e4fdda-bfbe-11e6-8ab5-5c7a11765b48.png">

and for the `<table>` here is what I get on Chrome for Android:
![screenshot_20161211-162329](https://cloud.githubusercontent.com/assets/4030626/21081069/0bf76530-bfbf-11e6-9f79-282d556d3e72.png)

**Comment by kelyvin** [comment]
Uooooo okay thanks for bringing this to my attention! I will take a look at this asap

**Comment by kelyvin** [comment]
Thanks for bringing this to my attention, I have fixed both issues and you can now grab them in the latest release (https://github.com/kelyvin/caffeine-theme/releases/tag/v2.8.1)!

To resolve the table overflow on mobile,  I made tables horizontally scrollable on smaller devices. I may look into a more responsive solution in the future, but for now this should be an adequate fix that doesn't ruin the user experience.

Thanks!

**Comment by EKami** [comment]
Again, thanks a lot @kelyvin :)
