### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by panagorn** [kelyvin/caffeine-theme#29]
Hello,
Loving the theme! Nice work.

I want to create an about page like your. Do i have to make a new post and make it static page? When i tried that i saw the circle image in the centre but it also changed the top banner image. In your web site the banner image shows the cover photo. Thank you

**Comment by kelyvin** [comment]
Hi @panagorn, 

Glad to hear you're enjoying the theme so far! The about pages uses a partial called `material-cover` which is located here. https://github.com/kelyvin/caffeine-theme/blob/master/partials/material-cover.hbs

In that file, I specify the banner image to be used on the about page. You can specify a new image, or you can use the default blog cover that you set within the Ghost admin panel. 

Let me know if this helped answered your question.

Thanks!

**Comment by panagorn** [comment]
I created a static page but i just noticed that there is a page-aboud.hbs how can i configure my blog to use this?

**Comment by kelyvin** [comment]
Follow the instructions here and that should detail it for you. The same convention is used in this theme as well. 

http://academy.ghost.org/creating-a-custom-page-template-on-ghost/

**Comment by kelyvin** [comment]
HI @panagorn, I'm going to close this issue if you are no longer running into any problems. Feel free to reopen it if you still get stuck. Thanks!
