### ISSUE TITLE
Copyright information in footer.hbs is incorrect

### ISSUE THREAD

**Issue by francoisgervais** [kelyvin/caffeine-theme#31]
Hello! 

Great work on this theme! I did notice a small issue with copyright title:
https://github.com/francoisgervais/caffeine-theme/commit/c24597722a20b4771e60ed3825fe8346cdd19025

The way you have it right now, the page title is being relayed, which works on the main page but not in articles:
![](http://i.imgur.com/qsbD0dC.png)
![](http://i.imgur.com/mGc9s6X.png)
![](http://i.imgur.com/22sSvmF.png)

Change {{meta_title}} to {{@blog.title}} to fix this.

**Comment by kelyvin** [comment]
Thanks for finding this issue @francoisgervais! I have checked in the fix with the latest [v2.8.4 release](https://github.com/kelyvin/caffeine-theme/releases/tag/v2.8.4).
