### ISSUE TITLE
Navigation buttons spacing

### ISSUE THREAD

**Issue by francoisgervais** [kelyvin/caffeine-theme#32]
Hello,

Another quick issue & possible improvement: navigation buttons in the call to action container get squished when the screen width forces them on two lines. 

It's mostly an issue with mobile browsers, could be an issue in a normal browser if someone had a ton of navigation links.

![](http://i.imgur.com/RfWD3lN.png)
![](http://i.imgur.com/skfeCtq.png)

Fixed it on my end by adding a 5px vertical padding:
https://github.com/francoisgervais/caffeine-theme/commit/c1441d9e5f93093c17b5da5ad868e4351516a3af

**Comment by kelyvin** [comment]
Thanks for finding this issue @francoisgervais! I have checked in the fix with the latest [v2.8.4 release](https://github.com/kelyvin/caffeine-theme/releases/tag/v2.8.4).
