### ISSUE TITLE
Homepage blank when using any other JS injection besides JQuery on desktop

### ISSUE THREAD

**Issue by MatteoJoliveau** [kelyvin/caffeine-theme#35]
When I try to inject any other js library besides JQuery in the footer the homepage appears blank.
It works on mobile though.
Tested on two separated computer with both Chrome and Edge.

![image](https://cloud.githubusercontent.com/assets/9077612/23130324/52bd64e8-f786-11e6-8ec1-3999ffbdd9a8.png)

**Comment by kelyvin** [comment]
Hi @MatteoJoliveau, can you copy and paste me exactly what you put in your footer so I can test this? 

Thanks

**Comment by MatteoJoliveau** [comment]
Hi @kelyvin 
I just copied the snippets from caffeine's README.
```<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script type="text/javascript" src="https://unpkg.com/imagesloaded@4.1/imagesloaded.pkgd.min.js"></script>
<script type="text/javascript" src="https://unpkg.com/masonry-layout@4.0/dist/masonry.pkgd.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/scrollreveal.js/3.0.9/scrollreveal.min.js"></script>```

**Comment by kelyvin** [comment]
Hi @MatteoJoliveau, 

What version of ghost are you running? Also, can you paste a screenshot of the "code injection" section of your admin console? I am not running into this issue, so I'm trying to narrow down potential issues. Thanks for the help!

**Comment by MatteoJoliveau** [comment]
I'm running Ghost 1.11.4 inside a container with the official Docker image. 
Here is a screenshot of the code injection page.
![image](https://cloud.githubusercontent.com/assets/9077612/23205248/70cb2a9c-f8e9-11e6-9bf4-d209dff73359.png)

**Comment by kelyvin** [comment]
I'm also running Ghost 0.11.4 and copy and pasted everything that you have into my code injection and didn't run into any issues. I also doubt the Docker image is causing the issues. 

Can you try opening the chrome developer tools and capturing the screenshot of the console and let me know what error messages you see? I wonder if it has to do with the content of one of your blog posts that is conflicting with one of the javascript libraries. For example, I had an issue with injecting `<iframe>` in my blog post before, and then had to check in a fix for that.

**Comment by kelyvin** [comment]
Since there have been no recent comments, I will close this for now. Feel free to reopen if you continue to run into any issues .
