### ISSUE TITLE
About code highlight

### ISSUE THREAD

**Issue by WangRicky** [kelyvin/caffeine-theme#44]
I want to change code highlight color,how should I do?if you can provide some options to fast change code block color,It is very friendly to people who can't use sass.
And I want to modify markdown style or use ghost default style,which files should I modify?
Thanks!

**Comment by kelyvin** [comment]
HI @WangRicky, 

This theme uses [PrismJS](http://prismjs.com/) for all code syntax highlighting and the current code theme I'm using is called `okaida`. 

If you'd like to switch out the code highlight color, feel free to fork this project and simply change the theme within the `gulpfile.js` as shown here: https://github.com/kelyvin/caffeine-theme/blob/c4ee52da126c1f1f9223121683f83d82cc99f7bc/gulpfile.js#L60

Hope that helps!
Kelvin
