### ISSUE TITLE
PageSpeed Insights with caffeine-theme shows the attached screenshots 

### ISSUE THREAD

**Issue by haimari** [kelyvin/caffeine-theme#45]
maybe some improvement can be done on "../assets/css/caffeine-theme.css"

![capture4](https://cloud.githubusercontent.com/assets/11332517/25776157/7c280026-32bf-11e7-93e1-eb75e9b5dafc.PNG)

**Comment by haimari** [comment]
Maybe this will help,
https://github.com/filamentgroup/loadCSS/blob/master/README.md

**Comment by jusuchin85** [comment]
This makes sense, but after discussion with @kelyvin in #56 , it's best we leave this from the main code base (as implementing this will cause the site to flash with unstyled HTML before the CSS kicks in).

If you would prefer, we would suggest implementing LoadCSS on your site 😃

**Comment by kelyvin** [comment]
Yep agree with jasuchin85's reply, will close this for now.
