### ISSUE TITLE
Blinking occurs when the mouse cursor is placed over the code text

### ISSUE THREAD

**Issue by archervanderwaal** [kelyvin/caffeine-theme#77]
When I use this theme and post, Blinking occurs when the mouse cursor is placed over the code text.

**Comment by kelyvin** [comment]
When the mouse cursor is placed over code text, the theme darkens the code block so that it's easier to read. 
However, if you're experiencing an issue than what I just described, can you provide further detail? What browser are you using? Is it repeatedly blinking? Can you provide a video/gif/screenshot of what's happening?

**Comment by archervanderwaal** [comment]
https://resources.archervanderwaal.com/show-issue.mp4

If I want to ban this phenomenon, what should I do? In addition, I would like to ask if I can't make the syntax highlighting using prismjs. What should I do with the correct method?

**Comment by kelyvin** [comment]
Oh wow can't believe I haven't noticed that before. Good catch. I will submit a patch fix tonight to resolve the issue. 

For prismjs, I sent you a direct message, but here's a recap of how to enable it: All you need to do is write your code in a code block and then add the name of the language after your first set of backticks, like so: 

```javascript

![Screen Shot 2019-03-26 at 2 18 37 PM](https://user-images.githubusercontent.com/1530102/55046690-a41b0600-4fff-11e9-9a5f-50be208a154d.png)

**Comment by archervanderwaal** [comment]
ok, thanks.

**Comment by kelyvin** [comment]
@archervanderwaal This issue has now been fixed and I have updated the latest release (https://github.com/kelyvin/caffeine-theme/releases/tag/v4.1.0). 

You should be good to go now. Thanks for reporting it!
