### ISSUE TITLE
How to remove the splash screen?

### ISSUE THREAD

**Issue by Abhi347** [kelyvin/caffeine-theme#9]
Hey there,
Thanks a lot for the theme. Just wanted to know, how can I remove the splash screen and move directly to the home?

**Comment by kelyvin** [comment]
Hi @Abhi347,

At the moment I haven't implemented an easy way to remove the splash screen and it will always be there by default. I will come up with a better solution in the following week to make this feature available easily for you. 

I haven't tested this thoroughly, but you can try opening the `cover.js` file and commenting out the following line: 

```
if (CaffeineTheme.is("page", "home")) {
        if (!CaffeineTheme.isOpen()) {
            return _expandCover();
        }
    }
```

This may be good enough for now until I come up with an easier solution.

Thanks!
Kelvin

**Comment by Abhi347** [comment]
Hi @kelyvin ,
I tried it, but it doesn't work. I can still see the splash. Let me know if there's any better way.

**Comment by kelyvin** [comment]
Hi @Abhi347, 

Thanks a bunch for your patience. I have been away on vacation and finally had the chance to catch up on these issues. I have made a feature enhancement to resolve your issue. The documentation on how to do this is available in the following section of the [README](https://github.com/kelyvin/caffeine-theme#disable-cover).  

You can now get this feature from my latest [v2.7.6 release](https://github.com/kelyvin/caffeine-theme/releases/tag/v2.7.6).

**Comment by rudeyak** [comment]
Awesome!
